/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.BookUserDAO;

import com.onway.fyapp.common.dal.dataobject.BookUserDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.BookUserDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisBookUserDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisBookUserDAO extends SqlMapClientDaoSupport implements BookUserDAO {
	/**
	 *  Insert one <tt>BookUserDO</tt> object to DB table <tt>vr_book_user</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_book_user(ID,USER_ID,BOOK_ID,DELETE_FLG,LOCAL_FLG,VERSION,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param bookUser
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(BookUserDO bookUser) throws DataAccessException {
    	if (bookUser == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-BOOK-USER-INSERT", bookUser);

        return bookUser.getId();
    }

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select BOOK_ID from vr_book_user where ((USER_ID = ?) AND (DELETE_FLG = ?)) order by GMT_MODIFIED DESC</tt>
	 *
	 *	@param userId
	 *	@param deleteFlg
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 
    public List<String> queryShelfByUserId(String userId, String deleteFlg) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("deleteFlg", deleteFlg);

        return getSqlMapClientTemplate().queryForList("MS-BOOK-USER-QUERY-SHELF-BY-USER-ID", param);

    }

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP</tt>
	 *
	 *	@param userId
	 *	@param bookIds
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatus(String userId, List bookIds) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("bookIds", bookIds);

        return getSqlMapClientTemplate().update("MS-BOOK-USER-UPDATE-STATUS", param);
    }

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateSort(String userId, String bookId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("bookId", bookId);

        return getSqlMapClientTemplate().update("MS-BOOK-USER-UPDATE-SORT", param);
    }

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP, DELETE_FLG=? where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param deleteFlg
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatusByBookIdAndUserId(String deleteFlg, String userId, String bookId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("deleteFlg", deleteFlg);
        param.put("userId", userId);
        param.put("bookId", bookId);

        return getSqlMapClientTemplate().update("MS-BOOK-USER-UPDATE-STATUS-BY-BOOK-ID-AND-USER-ID", param);
    }

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, DELETE_FLG, LOCAL_FLG, VERSION, GMT_CREATE, GMT_MODIFIED from vr_book_user where ((USER_ID = ?) AND (DELETE_FLG = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param userId
	 *	@param deleteFlg
	 *	@param bookId
	 *	@return BookUserDO
	 *	@throws DataAccessException
	 */	 
    public BookUserDO queryShelfByUserIdAndBookId(String userId, String deleteFlg, String bookId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("deleteFlg", deleteFlg);
        param.put("bookId", bookId);

        return (BookUserDO) getSqlMapClientTemplate().queryForObject("MS-BOOK-USER-QUERY-SHELF-BY-USER-ID-AND-BOOK-ID", param);

    }

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP, VERSION=? where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param version
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateBookVersion(String version, String userId, String bookId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("version", version);
        param.put("userId", userId);
        param.put("bookId", bookId);

        return getSqlMapClientTemplate().update("MS-BOOK-USER-UPDATE-BOOK-VERSION", param);
    }

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP, LOCAL_FLG=? where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param localFlg
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateBookLocalFlg(String localFlg, String userId, String bookId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("localFlg", localFlg);
        param.put("userId", userId);
        param.put("bookId", bookId);

        return getSqlMapClientTemplate().update("MS-BOOK-USER-UPDATE-BOOK-LOCAL-FLG", param);
    }

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, DELETE_FLG, LOCAL_FLG, VERSION, GMT_CREATE, GMT_MODIFIED from vr_book_user where ((USER_ID = ?) AND (LOCAL_FLG = ?)) order by GMT_MODIFIED DESC</tt>
	 *
	 *	@param userId
	 *	@param localFlg
	 *	@return List<BookUserDO>
	 *	@throws DataAccessException
	 */	 
    public List<BookUserDO> queryByUserIdAndLocalFlg(String userId, String localFlg) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("localFlg", localFlg);

        return getSqlMapClientTemplate().queryForList("MS-BOOK-USER-QUERY-BY-USER-ID-AND-LOCAL-FLG", param);

    }

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, DELETE_FLG, LOCAL_FLG, VERSION, GMT_CREATE, GMT_MODIFIED from vr_book_user where ((USER_ID = ?) AND (LOCAL_FLG = ?) AND (BOOK_ID = ?)) order by GMT_MODIFIED DESC</tt>
	 *
	 *	@param userId
	 *	@param localFlg
	 *	@param bookId
	 *	@return BookUserDO
	 *	@throws DataAccessException
	 */	 
    public BookUserDO queryByUserIdAndBookIdLocalFlg(String userId, String localFlg, String bookId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("localFlg", localFlg);
        param.put("bookId", bookId);

        return (BookUserDO) getSqlMapClientTemplate().queryForObject("MS-BOOK-USER-QUERY-BY-USER-ID-AND-BOOK-ID-LOCAL-FLG", param);

    }

}