/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.BookHandleDAO;

import com.onway.fyapp.common.dal.dataobject.BookHandleDO;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.BookHandleDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_handle.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisBookHandleDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisBookHandleDAO extends SqlMapClientDaoSupport implements BookHandleDAO {
	/**
	 *  Insert one <tt>BookHandleDO</tt> object to DB table <tt>vr_book_handle</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_book_handle(ID,USER_ID,BOOK_ID,TYPE,HAND_COUNT,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param bookHandle
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(BookHandleDO bookHandle) throws DataAccessException {
    	if (bookHandle == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-BOOK-HANDLE-INSERT", bookHandle);

        return bookHandle.getId();
    }

	/**
	 *  Update DB table <tt>vr_book_handle</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_handle set GMT_MODIFIED=CURRENT_TIMESTAMP, HAND_COUNT=(HAND_COUNT + 1) where ((USER_ID = ?) AND (BOOK_ID = ?) AND (TYPE = ?))</tt>
	 *
	 *	@param userId
	 *	@param bookId
	 *	@param type
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByUserId(String userId, String bookId, String type) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("bookId", bookId);
        param.put("type", type);

        return getSqlMapClientTemplate().update("MS-BOOK-HANDLE-UPDATE-BY-USER-ID", param);
    }

	/**
	 *  Query DB table <tt>vr_book_handle</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, TYPE, HAND_COUNT, GMT_CREATE, GMT_MODIFIED from vr_book_handle where ((USER_ID = ?) AND (BOOK_ID = ?) AND (TYPE = ?))</tt>
	 *
	 *	@param userId
	 *	@param bookId
	 *	@param type
	 *	@return BookHandleDO
	 *	@throws DataAccessException
	 */	 
    public BookHandleDO queryByUserIdAndBookIdAndType(String userId, String bookId, String type) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("bookId", bookId);
        param.put("type", type);

        return (BookHandleDO) getSqlMapClientTemplate().queryForObject("MS-BOOK-HANDLE-QUERY-BY-USER-ID-AND-BOOK-ID-AND-TYPE", param);

    }

}