/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.DownloadLogDAO;

import com.onway.fyapp.common.dal.dataobject.DownloadLogDO;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.DownloadLogDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_download_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisDownloadLogDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisDownloadLogDAO extends SqlMapClientDaoSupport implements DownloadLogDAO {
	/**
	 *  Insert one <tt>DownloadLogDO</tt> object to DB table <tt>vr_download_log</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_download_log(ID,USER_ID,BOOK_ID,INTERFACES,DOWNLOAD_SPEED,IS_SUCCESS,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param downloadLog
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(DownloadLogDO downloadLog) throws DataAccessException {
    	if (downloadLog == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-DOWNLOAD-LOG-INSERT", downloadLog);

        return downloadLog.getId();
    }

	/**
	 *  Query DB table <tt>vr_download_log</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_download_log</tt>
	 *
	 *	@param userId
	 *	@param bookId
	 *	@return DownloadLogDO
	 *	@throws DataAccessException
	 */	 
    public DownloadLogDO queryByUserIdAndBookId(String userId, String bookId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("bookId", bookId);

        return (DownloadLogDO) getSqlMapClientTemplate().queryForObject("MS-DOWNLOAD-LOG-QUERY-BY-USER-ID-AND-BOOK-ID", param);

    }

	/**
	 *  Update DB table <tt>vr_download_log</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_download_log set GMT_MODIFIED=CURRENT_TIMESTAMP, INTERFACES=? where (ID = ?)</tt>
	 *
	 *	@param interfaces
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByUserId(String interfaces, int id) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("interfaces", interfaces);
        param.put("id", new Integer(id));

        return getSqlMapClientTemplate().update("MS-DOWNLOAD-LOG-UPDATE-BY-USER-ID", param);
    }

	/**
	 *  Update DB table <tt>vr_download_log</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_download_log set GMT_MODIFIED=CURRENT_TIMESTAMP, DOWNLOAD_SPEED=?, IS_SUCCESS=? where (ID = ?)</tt>
	 *
	 *	@param downloadSpeed
	 *	@param isSuccess
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateSpeedByUserId(String downloadSpeed, String isSuccess, int id) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("downloadSpeed", downloadSpeed);
        param.put("isSuccess", isSuccess);
        param.put("id", new Integer(id));

        return getSqlMapClientTemplate().update("MS-DOWNLOAD-LOG-UPDATE-SPEED-BY-USER-ID", param);
    }

}