/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.FunctionsPointLogDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>vr_functions_point_log</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_functions_point_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: FunctionsPointLogDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface FunctionsPointLogDAO {
	/**
	 *  Insert one <tt>FunctionsPointLogDO</tt> object to DB table <tt>vr_functions_point_log</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_functions_point_log(ID,USER_ID,MODEL_ID,INTERFACES,OPERATION_TYPE,OPERATION_COUNT,POSITION,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param functionsPointLog
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(FunctionsPointLogDO functionsPointLog) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_functions_point_log</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_functions_point_log set GMT_MODIFIED=CURRENT_TIMESTAMP</tt>
	 *
	 *	@param userId
	 *	@param interfaces
	 *	@param type
	 *	@param position
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByUserId(String userId, String interfaces, String type, String position) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_functions_point_log</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_functions_point_log</tt>
	 *
	 *	@param userId
	 *	@param interfaces
	 *	@param type
	 *	@param position
	 *	@return FunctionsPointLogDO
	 *	@throws DataAccessException
	 */	 
    public FunctionsPointLogDO queryByUserIdAndFunction(String userId, String interfaces, String type, String position) throws DataAccessException;

}