/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>vr_ad</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_ad.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: AdDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class AdDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>AD_TITLE</tt>.
	 */
	private String adTitle;

	/**
	 * This property corresponds to db column <tt>AD_DESC</tt>.
	 */
	private String adDesc;

	/**
	 * This property corresponds to db column <tt>AD_POSTER</tt>.
	 */
	private String adPoster;

	/**
	 * This property corresponds to db column <tt>AD_CONTENT</tt>.
	 */
	private String adContent;

	/**
	 * This property corresponds to db column <tt>AD_DAY</tt>.
	 */
	private int adDay;

	/**
	 * This property corresponds to db column <tt>AD_TYPE</tt>.
	 */
	private String adType;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>adTitle</tt>.
     *
     * @return property value of adTitle
     */
	public String getAdTitle() {
		return adTitle;
	}
	
	/**
	 * Setter method for property <tt>adTitle</tt>.
	 * 
	 * @param adTitle value to be assigned to property adTitle
     */
	public void setAdTitle(String adTitle) {
		this.adTitle = adTitle;
	}

    /**
     * Getter method for property <tt>adDesc</tt>.
     *
     * @return property value of adDesc
     */
	public String getAdDesc() {
		return adDesc;
	}
	
	/**
	 * Setter method for property <tt>adDesc</tt>.
	 * 
	 * @param adDesc value to be assigned to property adDesc
     */
	public void setAdDesc(String adDesc) {
		this.adDesc = adDesc;
	}

    /**
     * Getter method for property <tt>adPoster</tt>.
     *
     * @return property value of adPoster
     */
	public String getAdPoster() {
		return adPoster;
	}
	
	/**
	 * Setter method for property <tt>adPoster</tt>.
	 * 
	 * @param adPoster value to be assigned to property adPoster
     */
	public void setAdPoster(String adPoster) {
		this.adPoster = adPoster;
	}

    /**
     * Getter method for property <tt>adContent</tt>.
     *
     * @return property value of adContent
     */
	public String getAdContent() {
		return adContent;
	}
	
	/**
	 * Setter method for property <tt>adContent</tt>.
	 * 
	 * @param adContent value to be assigned to property adContent
     */
	public void setAdContent(String adContent) {
		this.adContent = adContent;
	}

    /**
     * Getter method for property <tt>adDay</tt>.
     *
     * @return property value of adDay
     */
	public int getAdDay() {
		return adDay;
	}
	
	/**
	 * Setter method for property <tt>adDay</tt>.
	 * 
	 * @param adDay value to be assigned to property adDay
     */
	public void setAdDay(int adDay) {
		this.adDay = adDay;
	}

    /**
     * Getter method for property <tt>adType</tt>.
     *
     * @return property value of adType
     */
	public String getAdType() {
		return adType;
	}
	
	/**
	 * Setter method for property <tt>adType</tt>.
	 * 
	 * @param adType value to be assigned to property adType
     */
	public void setAdType(String adType) {
		this.adType = adType;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
