/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>vr_ontime</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_ontime.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: OntimeDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class OntimeDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>START_TIME</tt>.
	 */
	private Date startTime;

	/**
	 * This property corresponds to db column <tt>END_TIME</tt>.
	 */
	private Date endTime;

	/**
	 * This property corresponds to db column <tt>IMEI</tt>.
	 */
	private String imei;

	/**
	 * This property corresponds to db column <tt>QUIT_INTERFACE</tt>.
	 */
	private String quitInterface;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>startTime</tt>.
     *
     * @return property value of startTime
     */
	public Date getStartTime() {
		return startTime;
	}
	
	/**
	 * Setter method for property <tt>startTime</tt>.
	 * 
	 * @param startTime value to be assigned to property startTime
     */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

    /**
     * Getter method for property <tt>endTime</tt>.
     *
     * @return property value of endTime
     */
	public Date getEndTime() {
		return endTime;
	}
	
	/**
	 * Setter method for property <tt>endTime</tt>.
	 * 
	 * @param endTime value to be assigned to property endTime
     */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

    /**
     * Getter method for property <tt>imei</tt>.
     *
     * @return property value of imei
     */
	public String getImei() {
		return imei;
	}
	
	/**
	 * Setter method for property <tt>imei</tt>.
	 * 
	 * @param imei value to be assigned to property imei
     */
	public void setImei(String imei) {
		this.imei = imei;
	}

    /**
     * Getter method for property <tt>quitInterface</tt>.
     *
     * @return property value of quitInterface
     */
	public String getQuitInterface() {
		return quitInterface;
	}
	
	/**
	 * Setter method for property <tt>quitInterface</tt>.
	 * 
	 * @param quitInterface value to be assigned to property quitInterface
     */
	public void setQuitInterface(String quitInterface) {
		this.quitInterface = quitInterface;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
