/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>vr_phone</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_phone.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: PhoneDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class PhoneDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>PHONE_TYPE</tt>.
	 */
	private String phoneType;

	/**
	 * This property corresponds to db column <tt>IMEI</tt>.
	 */
	private String imei;

	/**
	 * This property corresponds to db column <tt>SYS_VERSION</tt>.
	 */
	private String sysVersion;

	/**
	 * This property corresponds to db column <tt>PROVINCE</tt>.
	 */
	private String province;

	/**
	 * This property corresponds to db column <tt>CITY</tt>.
	 */
	private String city;

	/**
	 * This property corresponds to db column <tt>AREA</tt>.
	 */
	private String area;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>phoneType</tt>.
     *
     * @return property value of phoneType
     */
	public String getPhoneType() {
		return phoneType;
	}
	
	/**
	 * Setter method for property <tt>phoneType</tt>.
	 * 
	 * @param phoneType value to be assigned to property phoneType
     */
	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

    /**
     * Getter method for property <tt>imei</tt>.
     *
     * @return property value of imei
     */
	public String getImei() {
		return imei;
	}
	
	/**
	 * Setter method for property <tt>imei</tt>.
	 * 
	 * @param imei value to be assigned to property imei
     */
	public void setImei(String imei) {
		this.imei = imei;
	}

    /**
     * Getter method for property <tt>sysVersion</tt>.
     *
     * @return property value of sysVersion
     */
	public String getSysVersion() {
		return sysVersion;
	}
	
	/**
	 * Setter method for property <tt>sysVersion</tt>.
	 * 
	 * @param sysVersion value to be assigned to property sysVersion
     */
	public void setSysVersion(String sysVersion) {
		this.sysVersion = sysVersion;
	}

    /**
     * Getter method for property <tt>province</tt>.
     *
     * @return property value of province
     */
	public String getProvince() {
		return province;
	}
	
	/**
	 * Setter method for property <tt>province</tt>.
	 * 
	 * @param province value to be assigned to property province
     */
	public void setProvince(String province) {
		this.province = province;
	}

    /**
     * Getter method for property <tt>city</tt>.
     *
     * @return property value of city
     */
	public String getCity() {
		return city;
	}
	
	/**
	 * Setter method for property <tt>city</tt>.
	 * 
	 * @param city value to be assigned to property city
     */
	public void setCity(String city) {
		this.city = city;
	}

    /**
     * Getter method for property <tt>area</tt>.
     *
     * @return property value of area
     */
	public String getArea() {
		return area;
	}
	
	/**
	 * Setter method for property <tt>area</tt>.
	 * 
	 * @param area value to be assigned to property area
     */
	public void setArea(String area) {
		this.area = area;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
}
