/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>vr_user_login_log</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_user_login_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: UserLoginLogDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class UserLoginLogDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>LOGIN_TYPE</tt>.
	 */
	private String loginType;

	/**
	 * This property corresponds to db column <tt>LOGIN_COUNT</tt>.
	 */
	private int loginCount;

	/**
	 * This property corresponds to db column <tt>IP</tt>.
	 */
	private String ip;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>loginType</tt>.
     *
     * @return property value of loginType
     */
	public String getLoginType() {
		return loginType;
	}
	
	/**
	 * Setter method for property <tt>loginType</tt>.
	 * 
	 * @param loginType value to be assigned to property loginType
     */
	public void setLoginType(String loginType) {
		this.loginType = loginType;
	}

    /**
     * Getter method for property <tt>loginCount</tt>.
     *
     * @return property value of loginCount
     */
	public int getLoginCount() {
		return loginCount;
	}
	
	/**
	 * Setter method for property <tt>loginCount</tt>.
	 * 
	 * @param loginCount value to be assigned to property loginCount
     */
	public void setLoginCount(int loginCount) {
		this.loginCount = loginCount;
	}

    /**
     * Getter method for property <tt>ip</tt>.
     *
     * @return property value of ip
     */
	public String getIp() {
		return ip;
	}
	
	/**
	 * Setter method for property <tt>ip</tt>.
	 * 
	 * @param ip value to be assigned to property ip
     */
	public void setIp(String ip) {
		this.ip = ip;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
