/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.BookSectionDAO;

import com.onway.fyapp.common.dal.dataobject.BookSectionDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.BookSectionDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_sections.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisBookSectionDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisBookSectionDAO extends SqlMapClientDaoSupport implements BookSectionDAO {
	/**
	 *  Query DB table <tt>vr_book_sections</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, MODEL_ID, SECTION_ID, CHAPTER_ID, SECTION_NAME, GMT_CREATE, GMT_MODIFIED from vr_book_sections where (CHAPTER_ID = ?)</tt>
	 *
	 *	@param chapterId
	 *	@return List<BookSectionDO>
	 *	@throws DataAccessException
	 */	 
    public List<BookSectionDO> querySectionByChapterId(String chapterId) throws DataAccessException {

 
        return getSqlMapClientTemplate().queryForList("MS-BOOK-SECTION-QUERY-SECTION-BY-CHAPTER-ID", chapterId);

    }

}