/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.BookHandleDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.HashMap;
import com.onway.fyapp.common.dal.vo.BookHandleVO;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>vr_book_handle</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_handle.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: BookHandleDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface BookHandleDAO {
	/**
	 *  Query DB table <tt>vr_book_handle</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_book_handle where (1 = 1)</tt>
	 *
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   selectHandle() throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_book_handle</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_book_handle</tt>
	 *
	 *	@param userName
	 *	@param bookName
	 *	@param offset
	 *	@param limit
	 *	@return List<BookHandleVO>
	 *	@throws DataAccessException
	 */	 
    public  List<BookHandleVO>   selectByQuery(String userName, String bookName, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_book_handle</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from vr_book_handle</tt>
	 *
	 *	@param userName
	 *	@param bookName
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   selectCountByQuery(String userName, String bookName) throws DataAccessException;

}