/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.VersionDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.HashMap;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>vr_version</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_version.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: VersionDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface VersionDAO {
	/**
	 *  Query DB table <tt>vr_version</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_version</tt>
	 *
	 *	@param versionNum
	 *	@param versionType
	 *	@param status
	 *	@param offset
	 *	@param limit
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public  List<Map<String,Object>>   selectVersion(String versionNum, String versionType, String status, Integer offset, Integer limit) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_version</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select count(1) from vr_version</tt>
	 *
	 *	@param versionNum
	 *	@param versionType
	 *	@param status
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   selectVersionCount(String versionNum, String versionType, String status) throws DataAccessException;

	/**
	 *  Insert one <tt>VersionDO</tt> object to DB table <tt>vr_version</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_version(VERSION_NUM,VERSION_TYPE,STATUS,DOWNLOAD_URL,MEMO,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param version
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insert(VersionDO version) throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>vr_version</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from vr_version where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   delete(int id) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_version</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_version set VERSION_NUM=?, VERSION_TYPE=?, STATUS=?, DOWNLOAD_URL=?, MEMO=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ID = ?)</tt>
	 *
	 *	@param versionNum
	 *	@param versionType
	 *	@param status
	 *	@param downloadUrl
	 *	@param memo
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updatVersion(String versionNum, String versionType, String status, String downloadUrl, String memo, int id) throws DataAccessException;

}