/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.BookVersionDAO;

import com.onway.fyapp.common.dal.dataobject.BookVersionDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Date;

import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.BookVersionDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_version.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisBookVersionDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisBookVersionDAO extends SqlMapClientDaoSupport implements BookVersionDAO {
	/**
	 *  Query DB table <tt>vr_book_version</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, BOOK_VERSION_ID, BOOK_ID, REVISE_NUM, CHANGE_LOG, STATUS, MEMO, GMT_CREATE, GMT_MODIFIED from vr_book_version</tt>
	 *
	 *	@return List<BookVersionDO>
	 *	@throws DataAccessException
	 */	 
    public  List<BookVersionDO>   loadAllVersion() throws DataAccessException {


        return getSqlMapClientTemplate().queryForList("MS-BOOK-VERSION-LOAD-ALL-VERSION", null);

    }

	/**
	 *  Query DB table <tt>vr_book_version</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_book_version</tt>
	 *
	 *	@param bookId
	 *	@return BookVersionDO
	 *	@throws DataAccessException
	 */	 
    public  BookVersionDO   selectBookVersionByBookId(String bookId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("bookId", bookId);

	        return (BookVersionDO) getSqlMapClientTemplate().queryForObject("MS-BOOK-VERSION-SELECT-BOOK-VERSION-BY-BOOK-ID", param);
		
    }

	/**
	 *  Update DB table <tt>vr_book_version</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_version set REVISE_NUM=?, CHANGE_LOG=?, STATUS=?, MEMO=?, GMT_MODIFIED=? where (ID = ?)</tt>
	 *
	 *	@param reviseNum
	 *	@param changeLog
	 *	@param status
	 *	@param memo
	 *	@param gmtModified
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   updateBookVersionByBookId(String reviseNum, String changeLog, String status, String memo, Date gmtModified, int id) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("reviseNum", reviseNum);
        param.put("changeLog", changeLog);
        param.put("status", status);
        param.put("memo", memo);
        param.put("gmtModified", gmtModified);
        param.put("id", new Integer(id));

        return getSqlMapClientTemplate().update("MS-BOOK-VERSION-UPDATE-BOOK-VERSION-BY-BOOK-ID", param);
    }

	/**
	 *  Insert one <tt>BookVersionDO</tt> object to DB table <tt>vr_book_version</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_book_version(BOOK_VERSION_ID,BOOK_ID,REVISE_NUM,CHANGE_LOG,STATUS,MEMO,GMT_CREATE) values (?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param bookVersion
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public  int   insertBookVersion(BookVersionDO bookVersion) throws DataAccessException {
    	if (bookVersion == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-BOOK-VERSION-INSERT-BOOK-VERSION", bookVersion);

        return bookVersion.getId();
    }

}