/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>vr_download_log</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_download_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: DownloadLogDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class DownloadLogDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>USER_ID</tt>.
	 */
	private String userId;

	/**
	 * This property corresponds to db column <tt>BOOK_ID</tt>.
	 */
	private String bookId;

	/**
	 * This property corresponds to db column <tt>INTERFACES</tt>.
	 */
	private String interfaces;

	/**
	 * This property corresponds to db column <tt>DOWNLOAD_SPEED</tt>.
	 */
	private String downloadSpeed;

	/**
	 * This property corresponds to db column <tt>IS_SUCCESS</tt>.
	 */
	private String isSuccess;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>userId</tt>.
     *
     * @return property value of userId
     */
	public String getUserId() {
		return userId;
	}
	
	/**
	 * Setter method for property <tt>userId</tt>.
	 * 
	 * @param userId value to be assigned to property userId
     */
	public void setUserId(String userId) {
		this.userId = userId;
	}

    /**
     * Getter method for property <tt>bookId</tt>.
     *
     * @return property value of bookId
     */
	public String getBookId() {
		return bookId;
	}
	
	/**
	 * Setter method for property <tt>bookId</tt>.
	 * 
	 * @param bookId value to be assigned to property bookId
     */
	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

    /**
     * Getter method for property <tt>interfaces</tt>.
     *
     * @return property value of interfaces
     */
	public String getInterfaces() {
		return interfaces;
	}
	
	/**
	 * Setter method for property <tt>interfaces</tt>.
	 * 
	 * @param interfaces value to be assigned to property interfaces
     */
	public void setInterfaces(String interfaces) {
		this.interfaces = interfaces;
	}

    /**
     * Getter method for property <tt>downloadSpeed</tt>.
     *
     * @return property value of downloadSpeed
     */
	public String getDownloadSpeed() {
		return downloadSpeed;
	}
	
	/**
	 * Setter method for property <tt>downloadSpeed</tt>.
	 * 
	 * @param downloadSpeed value to be assigned to property downloadSpeed
     */
	public void setDownloadSpeed(String downloadSpeed) {
		this.downloadSpeed = downloadSpeed;
	}

    /**
     * Getter method for property <tt>isSuccess</tt>.
     *
     * @return property value of isSuccess
     */
	public String getIsSuccess() {
		return isSuccess;
	}
	
	/**
	 * Setter method for property <tt>isSuccess</tt>.
	 * 
	 * @param isSuccess value to be assigned to property isSuccess
     */
	public void setIsSuccess(String isSuccess) {
		this.isSuccess = isSuccess;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
