/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.BookChapterDAO;

import com.onway.fyapp.common.dal.dataobject.BookChapterDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.BookChapterDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_chapter.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisBookChapterDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisBookChapterDAO extends SqlMapClientDaoSupport implements BookChapterDAO {
	/**
	 *  Query DB table <tt>vr_book_chapter</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, BOOK_ID, CHAPTER_ID, CHAPTER_NAME, GMT_CREATE, GMT_MODIFIED from vr_book_chapter where (BOOK_ID = ?)</tt>
	 *
	 *	@param bookId
	 *	@return List<BookChapterDO>
	 *	@throws DataAccessException
	 */	 
    public List<BookChapterDO> queryChapterByBookId(String bookId) throws DataAccessException {

 
        return getSqlMapClientTemplate().queryForList("MS-BOOK-CHAPTER-QUERY-CHAPTER-BY-BOOK-ID", bookId);

    }

}