/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.dataobject;

import com.onway.fyapp.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>vr_book_version</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_version.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: BookVersionDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class BookVersionDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>BOOK_VERSION_ID</tt>.
	 */
	private String bookVersionId;

	/**
	 * This property corresponds to db column <tt>BOOK_ID</tt>.
	 */
	private String bookId;

	/**
	 * This property corresponds to db column <tt>REVISE_NUM</tt>.
	 */
	private String reviseNum;

	/**
	 * This property corresponds to db column <tt>CHANGE_LOG</tt>.
	 */
	private String changeLog;

	/**
	 * This property corresponds to db column <tt>STATUS</tt>.
	 */
	private String status;

	/**
	 * This property corresponds to db column <tt>MEMO</tt>.
	 */
	private String memo;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>bookVersionId</tt>.
     *
     * @return property value of bookVersionId
     */
	public String getBookVersionId() {
		return bookVersionId;
	}
	
	/**
	 * Setter method for property <tt>bookVersionId</tt>.
	 * 
	 * @param bookVersionId value to be assigned to property bookVersionId
     */
	public void setBookVersionId(String bookVersionId) {
		this.bookVersionId = bookVersionId;
	}

    /**
     * Getter method for property <tt>bookId</tt>.
     *
     * @return property value of bookId
     */
	public String getBookId() {
		return bookId;
	}
	
	/**
	 * Setter method for property <tt>bookId</tt>.
	 * 
	 * @param bookId value to be assigned to property bookId
     */
	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

    /**
     * Getter method for property <tt>reviseNum</tt>.
     *
     * @return property value of reviseNum
     */
	public String getReviseNum() {
		return reviseNum;
	}
	
	/**
	 * Setter method for property <tt>reviseNum</tt>.
	 * 
	 * @param reviseNum value to be assigned to property reviseNum
     */
	public void setReviseNum(String reviseNum) {
		this.reviseNum = reviseNum;
	}

    /**
     * Getter method for property <tt>changeLog</tt>.
     *
     * @return property value of changeLog
     */
	public String getChangeLog() {
		return changeLog;
	}
	
	/**
	 * Setter method for property <tt>changeLog</tt>.
	 * 
	 * @param changeLog value to be assigned to property changeLog
     */
	public void setChangeLog(String changeLog) {
		this.changeLog = changeLog;
	}

    /**
     * Getter method for property <tt>status</tt>.
     *
     * @return property value of status
     */
	public String getStatus() {
		return status;
	}
	
	/**
	 * Setter method for property <tt>status</tt>.
	 * 
	 * @param status value to be assigned to property status
     */
	public void setStatus(String status) {
		this.status = status;
	}

    /**
     * Getter method for property <tt>memo</tt>.
     *
     * @return property value of memo
     */
	public String getMemo() {
		return memo;
	}
	
	/**
	 * Setter method for property <tt>memo</tt>.
	 * 
	 * @param memo value to be assigned to property memo
     */
	public void setMemo(String memo) {
		this.memo = memo;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
