/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.DownloadLogDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>vr_download_log</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_download_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: DownloadLogDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface DownloadLogDAO {
	/**
	 *  Insert one <tt>DownloadLogDO</tt> object to DB table <tt>vr_download_log</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_download_log(ID,USER_ID,BOOK_ID,INTERFACES,DOWNLOAD_SPEED,IS_SUCCESS,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param downloadLog
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(DownloadLogDO downloadLog) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_download_log</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_download_log</tt>
	 *
	 *	@param userId
	 *	@param bookId
	 *	@return DownloadLogDO
	 *	@throws DataAccessException
	 */	 
    public DownloadLogDO queryByUserIdAndBookId(String userId, String bookId) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_download_log</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_download_log set GMT_MODIFIED=CURRENT_TIMESTAMP, INTERFACES=? where (ID = ?)</tt>
	 *
	 *	@param interfaces
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByUserId(String interfaces, int id) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_download_log</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_download_log set GMT_MODIFIED=CURRENT_TIMESTAMP, DOWNLOAD_SPEED=?, IS_SUCCESS=? where (ID = ?)</tt>
	 *
	 *	@param downloadSpeed
	 *	@param isSuccess
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateSpeedByUserId(String downloadSpeed, String isSuccess, int id) throws DataAccessException;

}