/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.UserLoginLogDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>vr_user_login_log</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_user_login_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: UserLoginLogDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface UserLoginLogDAO {
	/**
	 *  Insert one <tt>UserLoginLogDO</tt> object to DB table <tt>vr_user_login_log</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_user_login_log(ID,USER_ID,LOGIN_TYPE,LOGIN_COUNT,IP,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param userLoginLog
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(UserLoginLogDO userLoginLog) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_user_login_log</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_user_login_log set GMT_MODIFIED=CURRENT_TIMESTAMP, LOGIN_COUNT=(LOGIN_COUNT + 1) where ((USER_ID = ?) AND (LOGIN_TYPE = ?))</tt>
	 *
	 *	@param userId
	 *	@param loginType
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateByUserId(String userId, String loginType) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_user_login_log</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, LOGIN_TYPE, LOGIN_COUNT, IP, GMT_CREATE GMT_MODIFIED from vr_user_login_log where ((USER_ID = ?) AND (LOGIN_TYPE = ?))</tt>
	 *
	 *	@param userId
	 *	@param loginType
	 *	@return UserLoginLogDO
	 *	@throws DataAccessException
	 */	 
    public UserLoginLogDO queryByUserIdAndType(String userId, String loginType) throws DataAccessException;

}