/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.fyapp.common.dal.daointerface.OrderDAO;

import com.onway.fyapp.common.dal.dataobject.OrderDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.fyapp.common.dal.daointerface.OrderDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_order.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisOrderDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisOrderDAO extends SqlMapClientDaoSupport implements OrderDAO {
	/**
	 *  Insert one <tt>OrderDO</tt> object to DB table <tt>vr_order</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_order(ORDER_ID,USER_ID,PAY_STATUS,BOOK_ID,PRICE,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param order
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(OrderDO order) throws DataAccessException {
    	if (order == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-ORDER-INSERT", order);

        return order.getId();
    }

	/**
	 *  Query DB table <tt>vr_order</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_order</tt>
	 *
	 *	@param orderId
	 *	@param userId
	 *	@param status
	 *	@param bookId
	 *	@return OrderDO
	 *	@throws DataAccessException
	 */	 
    public OrderDO queryOrderByItem(String orderId, String userId, String status, String bookId) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("orderId", orderId);
        param.put("userId", userId);
        param.put("status", status);
        param.put("bookId", bookId);

        return (OrderDO) getSqlMapClientTemplate().queryForObject("MS-ORDER-QUERY-ORDER-BY-ITEM", param);

    }

	/**
	 *  Query DB table <tt>vr_order</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from vr_order</tt>
	 *
	 *	@param userId
	 *	@param status
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 
    public List<Map<String,Object>> queryOrderByUserId(String userId, String status) throws DataAccessException {

	Map<String,Object> param = new HashMap<String,Object>();

        param.put("userId", userId);
        param.put("status", status);

        return getSqlMapClientTemplate().queryForList("MS-ORDER-QUERY-ORDER-BY-USER-ID", param);

    }

	/**
	 *  Update DB table <tt>vr_order</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_order set PAY_STATUS=?, GMT_MODIFIED=CURRENT_TIMESTAMP where (ORDER_ID = ?)</tt>
	 *
	 *	@param payStatus
	 *	@param orderId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatusByOrderId(String payStatus, String orderId) throws DataAccessException {
        Map<String,Object> param = new HashMap<String,Object>();

        param.put("payStatus", payStatus);
        param.put("orderId", orderId);

        return getSqlMapClientTemplate().update("MS-ORDER-UPDATE-STATUS-BY-ORDER-ID", param);
    }

}