/**
 * yingyinglicai.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.fyapp.common.dal.daointerface;

import com.onway.fyapp.common.dal.dataobject.BookUserDO;
import org.springframework.dao.DataAccessException;
import java.util.List;
import java.util.Date;
import java.util.Map;

/**
 * A dao interface provides methods to access database table <tt>vr_book_user</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/vr_book_user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: BookUserDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface BookUserDAO {
	/**
	 *  Insert one <tt>BookUserDO</tt> object to DB table <tt>vr_book_user</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into vr_book_user(ID,USER_ID,BOOK_ID,DELETE_FLG,LOCAL_FLG,VERSION,GMT_CREATE,GMT_MODIFIED) values (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param bookUser
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(BookUserDO bookUser) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select BOOK_ID from vr_book_user where ((USER_ID = ?) AND (DELETE_FLG = ?)) order by GMT_MODIFIED DESC</tt>
	 *
	 *	@param userId
	 *	@param deleteFlg
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 
    public List<String> queryShelfByUserId(String userId, String deleteFlg) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP</tt>
	 *
	 *	@param userId
	 *	@param bookIds
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatus(String userId, List bookIds) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateSort(String userId, String bookId) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP, DELETE_FLG=? where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param deleteFlg
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateStatusByBookIdAndUserId(String deleteFlg, String userId, String bookId) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, DELETE_FLG, LOCAL_FLG, VERSION, GMT_CREATE, GMT_MODIFIED from vr_book_user where ((USER_ID = ?) AND (DELETE_FLG = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param userId
	 *	@param deleteFlg
	 *	@param bookId
	 *	@return BookUserDO
	 *	@throws DataAccessException
	 */	 
    public BookUserDO queryShelfByUserIdAndBookId(String userId, String deleteFlg, String bookId) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP, VERSION=? where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param version
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateBookVersion(String version, String userId, String bookId) throws DataAccessException;

	/**
	 *  Update DB table <tt>vr_book_user</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update vr_book_user set GMT_MODIFIED=CURRENT_TIMESTAMP, LOCAL_FLG=? where ((USER_ID = ?) AND (BOOK_ID = ?))</tt>
	 *
	 *	@param localFlg
	 *	@param userId
	 *	@param bookId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateBookLocalFlg(String localFlg, String userId, String bookId) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, DELETE_FLG, LOCAL_FLG, VERSION, GMT_CREATE, GMT_MODIFIED from vr_book_user where ((USER_ID = ?) AND (LOCAL_FLG = ?)) order by GMT_MODIFIED DESC</tt>
	 *
	 *	@param userId
	 *	@param localFlg
	 *	@return List<BookUserDO>
	 *	@throws DataAccessException
	 */	 
    public List<BookUserDO> queryByUserIdAndLocalFlg(String userId, String localFlg) throws DataAccessException;

	/**
	 *  Query DB table <tt>vr_book_user</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, BOOK_ID, DELETE_FLG, LOCAL_FLG, VERSION, GMT_CREATE, GMT_MODIFIED from vr_book_user where ((USER_ID = ?) AND (LOCAL_FLG = ?) AND (BOOK_ID = ?)) order by GMT_MODIFIED DESC</tt>
	 *
	 *	@param userId
	 *	@param localFlg
	 *	@param bookId
	 *	@return BookUserDO
	 *	@throws DataAccessException
	 */	 
    public BookUserDO queryByUserIdAndBookIdLocalFlg(String userId, String localFlg, String bookId) throws DataAccessException;

}